-- AlterTable
ALTER TABLE "Round" ALTER COLUMN "status" SET DEFAULT 'committed',
ALTER COLUMN "nonce" SET DATA TYPE TEXT,
ALTER COLUMN "rows" SET DEFAULT 12,
ALTER COLUMN "dropColumn" SET DEFAULT 6,
ALTER COLUMN "betCents" SET DEFAULT 100;
